St convert to hooks
kamsci/garden-aid pull request #2
Opened 2023-09-12 19:41 UTC by SamaadTurner

2023-09-12 20:05 UTC, kamsci requested changes
I don't see any components from the src/Gardens/SearchView folder changed. 

Can you go through and change those as well?

2023-09-12 20:05 UTC, kamsci commented on src/User/Profile.jsx
> +import ProfileView from "./ProfileView"
```suggestion
import ProfileView from "./ProfileView";
```

2023-09-12 20:05 UTC, kamsci commented on src/HelperComponents/PaginationComponent.jsx
> +        activePage;
```suggestion
```

random reference of activePage.. it doesn't do anything here, you already have activePage declared in the function. you can remove this line.

2023-09-13 05:02 UTC, SamaadTurner reviewed
got it.

2023-09-13 05:04 UTC, kamsci approved these changes

2023-09-13 05:04 UTC, merged